language: php
 
php:
  - 5.5
  - 5.4
  - 5.3
 
before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - mv ../MeTools plugins/MeTools
  - chmod -R 777 ../cakephp/app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
	public \$test = array(
    'datasource' => ''
	);
	public \$default = array(
	'datasource' => ''
	);
    }" > ../cakephp/app/Config/database.php